# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 21:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='statistics',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
